name: Clumsy Kitty Creations
favicon: null
layout_spectrum: 1
typography_spectrum: 0.59215
title: Clumsy Kitty Creations
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010300'
    - '#2e2e2e'
    - '#f2e2af'
    - '#be8a47'
    - '#79868e'
  brandStrength: 0.75
  lightness: 0.75
  saturation: 0.375
  rhythmicContrast: 0
purpose: []
