name: Clumsy Kitty Creations
favicon: null
layout_spectrum: 0.26342
typography_spectrum: 0.59215
title: Clumsy Kitty Creations
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.6875
  lightness: 0.7237063916400075
  saturation: 0.28445141785778105
  rhythmicContrast: 0.757230818271637
purpose: []
